### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by VolkovEvgenii** [VolkovEvgenii/kanbanBoard#1]
### HTML
- [ ] index.html (основная форма Рустам)
- [ ] addUser.html (форма добавления пользователя Рустам)
- [ ] addProject.html (фома добавления проекта Рустам)
### Code
- [ ] добавить EnityManager (Женя)
### Chat
- [ ] добавить chat (Богдан)
